# Generated by Django 2.1.14 on 2020-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200403_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='tx.svg', help_text='图像图片', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
