# Generated by Django 2.1.14 on 2020-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200403_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='img/touxiang.png', help_text='图像图片', null=True, upload_to='img', verbose_name='头像'),
        ),
    ]
