# Generated by Django 2.1.14 on 2020-05-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('api', models.CharField(max_length=1024, verbose_name='api')),
                ('method', models.CharField(max_length=32, verbose_name='请求方式')),
                ('api_name', models.CharField(max_length=1024, verbose_name='接口名称')),
                ('tag', models.CharField(max_length=1024, verbose_name='接口标签')),
                ('params_type', models.CharField(max_length=32, verbose_name='参数类型')),
                ('parameters', models.TextField()),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'API',
            },
        ),
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('model', models.CharField(max_length=64, verbose_name='所属模块')),
                ('method', models.CharField(max_length=2, verbose_name='请求方式')),
                ('url', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('type', models.IntegerField(verbose_name='参数类型')),
                ('params', models.TextField(verbose_name='请求参数')),
                ('checkType', models.CharField(max_length=32, verbose_name='校验类型')),
                ('checkText', models.TextField(verbose_name='校验值')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接口用例表',
                'verbose_name_plural': '接口用例表',
                'db_table': 'apicase',
            },
        ),
        migrations.CreateModel(
            name='APIcaseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.IntegerField(verbose_name='用例id')),
                ('case_name', models.CharField(max_length=1024, verbose_name='用例名称')),
                ('case_method', models.CharField(max_length=32, verbose_name='请求方式')),
                ('case_url', models.CharField(max_length=1024, verbose_name='请求地址')),
                ('case_headers', models.TextField(verbose_name='请求headers')),
                ('case_params', models.TextField(verbose_name='请求参数')),
                ('case_response', models.TextField(verbose_name='响应结果')),
                ('case_expect', models.TextField(verbose_name='期望结果')),
                ('case_stauts', models.CharField(max_length=12, verbose_name='case状态')),
                ('case_report', models.CharField(max_length=200, verbose_name='报告编号')),
                ('case_log', models.TextField()),
            ],
            options={
                'verbose_name': '用例报告详情',
                'verbose_name_plural': '用例报告详情',
                'db_table': 'case_reportInfo',
            },
        ),
        migrations.CreateModel(
            name='ApiILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('caseId', models.IntegerField(verbose_name='用例id')),
                ('caseUrl', models.TextField(verbose_name='接口url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'headers',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('model_name', models.CharField(max_length=64, verbose_name='模块名称')),
            ],
            options={
                'verbose_name': '模块表',
                'verbose_name_plural': '模块表',
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('project_address', models.CharField(max_length=1024, verbose_name='项目地址')),
                ('document', models.CharField(blank=True, max_length=1024, null=True, verbose_name='文档地址')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('R_Number', models.CharField(max_length=64, verbose_name='任务编号')),
                ('R_Env', models.CharField(max_length=128, verbose_name='执行环境')),
                ('R_project', models.CharField(max_length=10, verbose_name='所属项目')),
                ('R_CaseId', models.CharField(max_length=1024, verbose_name='报告用例id')),
                ('R_Status', models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已完成')], default=1, verbose_name='任务状态')),
                ('R_CaseSum', models.IntegerField(verbose_name='任务用例个数')),
                ('R_CasePass', models.IntegerField(blank=True, null=True, verbose_name='成功数')),
                ('R_CaseFail', models.IntegerField(blank=True, null=True, verbose_name='失败数')),
                ('R_StartTime', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务起始时间')),
                ('R_EndTime', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务结束时间')),
                ('R_Type', models.IntegerField(choices=[(1, '即时任务'), (2, '定时任务')], default=2, verbose_name='任务类型')),
            ],
            options={
                'verbose_name': '接口报告表',
                'verbose_name_plural': '接口报告表',
                'db_table': 'report',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Project', verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='headers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Project', verbose_name='所属项目id'),
        ),
        migrations.AddField(
            model_name='api',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Project', verbose_name='所属项目'),
        ),
    ]
