# Generated by Django 2.1.14 on 2020-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('case_params', models.TextField(verbose_name='用例请求参数')),
                ('case_check', models.TextField(verbose_name='断言')),
                ('case_extract', models.TextField(verbose_name='提取变量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
                'db_table': 'case',
            },
        ),
        migrations.RenameModel(
            old_name='APIcaseinfo',
            new_name='CaseReport',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='ApiILog',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='api',
            name='parameters',
            field=models.TextField(verbose_name='接口参数'),
        ),
        migrations.AlterModelTable(
            name='api',
            table='api',
        ),
        migrations.AlterModelTable(
            name='casereport',
            table='report_info',
        ),
        migrations.DeleteModel(
            name='ApiCase',
        ),
    ]
