# Generated by Django 2.2.8 on 2020-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoCeleryBeatClockedschedule',
        ),
        migrations.DeleteModel(
            name='DjangoCeleryBeatCrontabschedule',
        ),
        migrations.DeleteModel(
            name='DjangoCeleryBeatIntervalschedule',
        ),
        migrations.DeleteModel(
            name='DjangoCeleryBeatPeriodictask',
        ),
        migrations.DeleteModel(
            name='DjangoCeleryBeatPeriodictasks',
        ),
        migrations.DeleteModel(
            name='DjangoCeleryBeatSolarschedule',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.AddField(
            model_name='report',
            name='R_Type',
            field=models.IntegerField(choices=[(1, '即时任务'), (2, '定时任务')], default=1, verbose_name='任务类型'),
            preserve_default=False,
        ),
    ]
