# Generated by Django 2.1.14 on 2020-05-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200527_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.API', verbose_name='接口'),
            preserve_default=False,
        ),
    ]
