# Generated by Django 2.1.14 on 2020-05-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_case_case_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='product',
            new_name='project',
        ),
    ]
