# Generated by Django 2.1.14 on 2020-03-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200314_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIcaseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.IntegerField(verbose_name='用例id')),
                ('case_method', models.CharField(max_length=32, verbose_name='请求方式')),
                ('case_url', models.CharField(max_length=1024, verbose_name='请求地址')),
                ('case_headers', models.TextField(verbose_name='请求headers')),
                ('case_params', models.TextField(verbose_name='请求参数')),
                ('case_response', models.TextField(verbose_name='响应结果')),
                ('case_expect', models.TextField(verbose_name='期望结果')),
                ('case_stauts', models.CharField(max_length=12, verbose_name='case状态')),
                ('case_report', models.CharField(max_length=200, verbose_name='报告编号')),
            ],
            options={
                'verbose_name': '用例报告详情',
                'verbose_name_plural': '用例报告详情',
                'db_table': 'case_reportInfo',
            },
        ),
    ]
