# Generated by Django 2.1.14 on 2020-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_apicaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicaseinfo',
            name='case_name',
            field=models.CharField(default=2222, max_length=1024, verbose_name='用例名称'),
            preserve_default=False,
        ),
    ]
