# Generated by Django 2.1.14 on 2020-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_apicaseinfo_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicaseinfo',
            name='case_log',
            field=models.TextField(default=11111),
            preserve_default=False,
        ),
    ]
